frontend/controllers/BitcoinController.php
<?php
namespace frontend\controllers;

use Yii;

class BitcoinController extends \yii\web\Controller
{
    public $enableCsrfValidation = false;
    private $_blockchain = null;

    public function actionIndex()
    {
        $serverAdress = null;

        $clientAddress = Yii::$app->request->post('clientAdress');

        if (!empty($clientAddress)) {
            $serverAdress = $this->_getNewAddress($clientAddress);
        }
        //\yii\helpers\VarDumper::dump($clientAddress, 10, true);

        return $this->render('index',[
            'tableData' => $this->_getTableData(),
            'serverAdress' => $serverAdress
            ]);
    }

    private function _getAdresses()
    {
        $blockchain = $this->_getBlockchain();

        return $blockchain->Wallet->getAddresses();
    }

    private function _getTableData()
    {
        $adresses = $this->_getAdresses();

        //filter
        
        return $adresses;
    }

    private function _getNewAddress($label =  '')
    {
         $blockchain = $this->_getBlockchain();

         return $blockchain->Wallet->getNewAddress($label);
    }

    private function _getBlockchain()
    {
        if (empty($this->_blockchain)) {
            // Create the base Blockchain class instance
            $this->_blockchain = new \Blockchain\Blockchain();

            $this->_blockchain->Wallet->credentials(
                Yii::$app->params['blockchainId'],
                Yii::$app->params['blockchainPassword']
            );
        }

        return $this->_blockchain;
    }
}

frontend/views/layouts/main.php
<?php
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use frontend\assets\AppAsset;
use frontend\widgets\Alert;

/* @var $this \yii\web\View */
/* @var $content string */

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?> | x2Coin</title>
    <?php $this->head() ?>
</head>
<body>
	<!--<div class="vzlom" style="background: red; color: white; position: fixed; width: 100%; height: 100%; text-align: center; z-index: 99999; padding-top:20%"><h1>Ваш сайт взломали</h1></div>-->
    <?php $this->beginBody() ?>
    <div class="wrap">
        <?php
            NavBar::begin([
                'brandLabel' => 'x2Coin',
                'brandUrl' => Yii::$app->homeUrl,
                'options' => [
                    'class' => 'navbar-inverse navbar-fixed-top',
                ],
            ]);
            $menuItems = [                
                ['label' => 'Home', 'url' => ['/site/index']],
                ['label' => 'Bitcoin', 'url' => ['/bitcoin/index']],
                ['label' => 'About', 'url' => ['/site/about']],
                ['label' => 'Contact', 'url' => ['/site/contact']],
            ];
            if (Yii::$app->user->isGuest) {
                $menuItems[] = ['label' => 'Signup', 'url' => ['/site/signup']];
                $menuItems[] = ['label' => 'Login', 'url' => ['/site/login']];
            } else {
                $menuItems[] = [
                    'label' => 'Logout (' . Yii::$app->user->identity->username . ')',
                    'url' => ['/site/logout'],
                    'linkOptions' => ['data-method' => 'post']
                ];
            }
            echo Nav::widget([
                'options' => ['class' => 'navbar-nav navbar-right'],
                'items' => $menuItems,
            ]);
            NavBar::end();
        ?>

        <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= Alert::widget() ?>
        <?= $content ?>
        </div>
    </div>

    <footer class="footer">
        <div class="container">
        <p class="pull-left">&copy; x2Coin <?= date('Y') ?></p>
        <p class="pull-right"><?= Yii::powered() ?></p>
        </div>
    </footer>

    <?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>